---
- name: check diskspace
  hosts: servers
  tasks:
      - name: check diskspace
        shell: df -Ph | awk '/sd|loop|mapper/ {print $6,"에 마운트된",$1"\n"$2, "중 남은용량",$4"("100-$5"%)"}'
        register: result
      - name: log result
        debug:
            msg: '{{result}}'
      - name: alarm diskspace
        uri:
            url: 'https://ntfy.mcnal.net/ansible-alert'
            method: POST
            body: "{{inventory_hostname}} disk 상태\n\n{{result.stdout}}"
